export type RegionId = 'north' | 'oil_belt' | 'south' | 'islands';

export interface CountryDef {
  id: string;
  name: string;
  nameAr: string;
  region: RegionId;
  regionAr: string;
  resource: string;
  weakness: string;
  position: [number, number, number];
  color: [number, number, number];
}

export const MEDIUM_MAP_COUNTRIES: CountryDef[] = [
  {
    id: 'falconia',
    name: 'Falconia',
    nameAr: 'فالكونيا',
    region: 'north',
    regionAr: 'الشمال الصناعي',
    resource: 'تكنولوجيا + تصنيع',
    weakness: 'تستورد كل طاقتها',
    position: [-6, 0.3, 4],
    color: [0.35, 0.45, 0.65],
  },
  {
    id: 'northam',
    name: 'Northam',
    nameAr: 'نورثام',
    region: 'north',
    regionAr: 'الشمال الصناعي',
    resource: 'رأس مال + بنوك',
    weakness: 'حساسة للشائعات المالية',
    position: [-2, 0.3, 5],
    color: [0.4, 0.5, 0.7],
  },
  {
    id: 'ironfeld',
    name: 'Ironfeld',
    nameAr: 'إيرنفيلد',
    region: 'north',
    regionAr: 'الشمال الصناعي',
    resource: 'غذاء + صناعة',
    weakness: 'ديون تاريخية ضخمة',
    position: [2, 0.3, 4.5],
    color: [0.45, 0.55, 0.5],
  },
  {
    id: 'steelmark',
    name: 'Steelmark',
    nameAr: 'ستيلمارك',
    region: 'north',
    regionAr: 'الشمال الصناعي',
    resource: 'معادن + طاقة',
    weakness: 'يعتمد على سعر النفط',
    position: [6, 0.3, 3.5],
    color: [0.5, 0.45, 0.4],
  },
  {
    id: 'zahiran',
    name: 'Zahiran',
    nameAr: 'زهيران',
    region: 'oil_belt',
    regionAr: 'الحزام النفطي',
    resource: '40% من النفط العالمي',
    weakness: 'لا صناعة خارج النفط',
    position: [-4, 0.3, 0],
    color: [0.7, 0.55, 0.2],
  },
  {
    id: 'qaseria',
    name: 'Qaseria',
    nameAr: 'قاسريا',
    region: 'oil_belt',
    regionAr: 'الحزام النفطي',
    resource: 'نفط + ممر بري',
    weakness: 'ولاء متغير',
    position: [0, 0.3, 0.5],
    color: [0.75, 0.5, 0.15],
  },
  {
    id: 'miras',
    name: 'Miras',
    nameAr: 'ميراس',
    region: 'oil_belt',
    regionAr: 'الحزام النفطي',
    resource: 'غاز + مركز مالي',
    weakness: 'صغيرة وسهلة الحصار',
    position: [4, 0.3, -0.5],
    color: [0.65, 0.5, 0.25],
  },
  {
    id: 'copanga',
    name: 'Copanga',
    nameAr: 'كوبانغا',
    region: 'south',
    regionAr: 'القارة الجنوبية',
    resource: 'معادن نادرة',
    weakness: 'حكومة فاسدة',
    position: [-5, 0.3, -4],
    color: [0.3, 0.55, 0.35],
  },
  {
    id: 'sirania',
    name: 'Sirania',
    nameAr: 'سيرانيا',
    region: 'south',
    regionAr: 'القارة الجنوبية',
    resource: 'غذاء ضخم',
    weakness: 'ديون خارجية',
    position: [-1, 0.3, -4.5],
    color: [0.35, 0.6, 0.3],
  },
  {
    id: 'ndalu',
    name: 'Ndalu',
    nameAr: 'ندالو',
    region: 'south',
    regionAr: 'القارة الجنوبية',
    resource: 'ممر بحري + غاز',
    weakness: 'بنية تحتية ضعيفة',
    position: [3, 0.3, -4],
    color: [0.25, 0.5, 0.55],
  },
  {
    id: 'havaria',
    name: 'Havaria',
    nameAr: 'هافاريا',
    region: 'south',
    regionAr: 'القارة الجنوبية',
    resource: 'موارد مجهولة',
    weakness: 'اقتصاد في فوضى',
    position: [7, 0.3, -3.5],
    color: [0.4, 0.45, 0.5],
  },
  {
    id: 'kalmera',
    name: 'Kalmera',
    nameAr: 'كالميرا',
    region: 'islands',
    regionAr: 'الجزر التجارية',
    resource: 'بنوك سرية',
    weakness: 'تكشف حسابات المنافسين',
    position: [-7, 0.3, -7],
    color: [0.55, 0.65, 0.75],
  },
  {
    id: 'portica',
    name: 'Portica',
    nameAr: 'بورتيكا',
    region: 'islands',
    regionAr: 'الجزر التجارية',
    resource: 'رسوم عبور',
    weakness: 'هدف للخصوم',
    position: [0, 0.3, -7.5],
    color: [0.5, 0.6, 0.8],
  },
  {
    id: 'freeport',
    name: 'Freeport',
    nameAr: 'فريبورت',
    region: 'islands',
    regionAr: 'الجزر التجارية',
    resource: 'سوق موازٍ',
    weakness: 'خارج الرقابة',
    position: [7, 0.3, -7],
    color: [0.6, 0.55, 0.45],
  },
];
